name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      # CHEKCOUT REPOSITORY
      - name: Git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # SETUP HUGO
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        with:
          hugo-version: latest
          extended: true

      # DEPENDENCIES
      - name: Install npm dependencies
        run: npm ci

      # BUILD
      - name: Build Site
        env:
          TZ: "Europe/Warsaw"
        run: hugo --minify
